# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ARPAdata
                                 A QGIS plugin
 This plugin downloads the data from ARPA Lombardia API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-03
        copyright            : (C) 2021 by Mathilde Puche
        email                : mathilde-puche@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ARPAdata class from file ARPAdata.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .arpa_data import ARPAdata
    return ARPAdata(iface)
